//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line,Section,Block Number,Block Length (m),Block Grade (%),Speed Limit (Km/Hr),Infrastructure,,ELEVATION (M),CUMALTIVE ELEVATION (M),,
        ///Green,A,1,100,0.5,55,,,0.5,0.5,,
        ///Green,A,2,100,1,55,STATION; PIONEER,,1,1.5,,
        ///Green,A,3,100,1.5,55,,,1.5,3,,
        ///Green,B,4,100,2,55,,,2,5,,
        ///Green,B,5,100,3,55,,,3,8,,
        ///Green,B,6,100,4,55,,,4,12,,
        ///Green,C,7,100,5,55,,,5,17,,
        ///Green,C,8,100,0,55,,,0,17,,
        ///Green,C,9,100,-5,55,STATION; EDGEBROOK,,-5,12,,
        ///Green,C,10,100,-5,55,,,-5,7,,
        ///Green,C,11,100,-4,55,,,-4,3,,
        ///Green,C,12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string green {
            get {
                return ResourceManager.GetString("green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line,Section,Block Number,Block Length (m),Block Grade (%),Speed Limit (Km/Hr),Infrastructure,,ELEVATION (M),CUMALTIVE ELEVATION (M),,
        ///Red,A,1,50,0.5,40,,,0.25,0.25,,
        ///Red,A,2,50,1,40,,,0.50,0.75,,
        ///Red,A,3,50,1.5,40,,,0.75,1.50,,
        ///Red,B,4,50,2,40,,,1.00,2.50,,
        ///Red,B,5,50,1.5,40,,,0.75,3.25,,
        ///Red,B,6,50,1,40,,,0.50,3.75,,
        ///Red,C,7,75,0.5,40,STATION: SHADYSIDE,,0.38,4.13,,
        ///Red,C,8,75,0,40,,,0.00,4.13,,
        ///Red,C,9,75,0,40,SWITCH TO/FROM YARD,,0.00,4.13,,
        ///Red,D,10,75,0,40,,,0.00,4.13,,
        ///Red,D,11,75,-0.5,40, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
    }
}
